export type Publication = {
  category: "Journals" | "Conference Proceedings" | "Books" | "Book Chapters" | "Posters";
  authors: string;
  title: string;
  venue: string;
  year: number;
  details?: string;
  doi?: string;
  videos?: { label: string; url: string }[];
  posterUrl?: string;
  galleryId?: string;
};

export const publications: Publication[] = [
  { category: "Journals", authors: "V. Joseph, B.K. Sarkar, A. Chatterjee, S. Chaudhuri", title: "Fast nonsingular terminal sliding mode controller design for Francis turbine with electrohydraulic IGV: an experimental investigation", venue: "Proceedings of the Institution of Mechanical Engineers, Part I: Journal of Systems and Control Engineering", year: 2026, details: "Jan. 2026", doi: "10.1177/09596518251399972" },
  { category: "Journals", authors: "Y. Sheikh Kilo, R. Izadi-Zamanabadi, H. Ramezani, P. Gullo, S. Chaudhuri", title: "Cost-effective optimization for charging/discharging cycles of thermal energy ice storages in transcritical R744 supermarket refrigeration systems", venue: "Energy Conversion and Management", year: 2025, details: "vol. 334, 119790, Jun. 2025. ISSN 0196-8904", doi: "10.1016/j.enconman.2025.119790" },
  { category: "Journals", authors: "S. Paul, S. Das, M. Banerjea, S. Chaudhuri, B. Das", title: "The ATP-dependent DEAD-box RNA helicase Dbp2 regulates the glucose/nitrogen stress response in baker's yeast by modulating reversible nuclear retention and decay of SKS1 mRNA", venue: "Genetics", year: 2025, details: "vol. 229, no. 3, iyae221, Mar. 2025", doi: "10.1093/genetics/iyae221" },
  { category: "Journals", authors: "H. Ramezani, S. Chaudhuri, J. Jouffroy, A. Baurichter, S.M. Hansen", title: "On roll stabilisation using a canting keel", venue: "IEEE Transactions on Control Systems Technology", year: 2025, details: "vol. 33, no. 2, pp. 539–553, Mar. 2025 (early access Nov. 2024). ISSN 1558-0865", doi: "10.1109/TCST.2024.3494237", videos: [
    { label: "Water Tank Test for Conventional Keel (CK)", url: "https://youtu.be/N89cQXGlHnY" },
    { label: "Water Tank Test for Airkeel (AK)", url: "https://youtu.be/Ri43Zp2B0pI" },
    { label: "Field Test for Conventional Keel (CK)", url: "https://youtu.be/8M-48dO4nR0" },
    { label: "Field Test for Airkeel (AK)", url: "https://youtu.be/fORjzl04tpQ" },
    { label: "Simulation with Airkeel (AK)", url: "https://youtu.be/cY3Z3y2hikg" },
  ] },
  { category: "Journals", authors: "N. Taghva, S. Chaudhuri", title: "How language-specific and cross-linguistic factors affect speech rhythm", venue: "Estudios de Fonética Experimental", year: 2024, details: "vol. 33, pp. 169–190, Sep. 2024", doi: "10.1344/EFE-2024-33-169-190" },
  { category: "Journals", authors: "A. Sarkar, S. Dasmahapatra, S. Chaudhuri, R. Saha, S. Mookherjee, D. Sanyal", title: "A novel order-separated generalized feedforward design for motion control in energy-efficient electrohydraulic systems with proportional and integral feedback", venue: "ISA Transactions", year: 2024, details: "vol. 146, pp. 336–351, Jan. 2024. ISSN 0019-0578", doi: "10.1016/j.isatra.2024.01.012" },
  { category: "Journals", authors: "I. De, S. Sarkar, S. Chaudhuri, N. Mondal, N. Kumar", title: "Effect of dynamic swivelling torque and eccentricity on the design of compensator cylinders for a variable displacement axial piston pump", venue: "Jordan Journal of Mechanical and Industrial Engineering", year: 2023, details: "vol. 17, no. 2, pp. 255–268, Jun. 2023. ISSN 1995-6665", doi: "10.59038/jjmie/170209" },
  { category: "Journals", authors: "A. Sarkar, K. Maji, S. Chaudhuri, R. Saha, S. Mookherjee, D. Sanyal", title: "Actuation of an electrohydraulic manipulator with a novel feedforward compensation scheme and PID feedback in servo-proportional valves", venue: "Control Engineering Practice", year: 2023, details: "vol. 135, 105490, Mar. 2023. ISSN 0967-0661", doi: "10.1016/j.conengprac.2023.105490" },
  { category: "Journals", authors: "S. Sarkar, R. Mandal, N. Mondal, S. Chaudhuri, T. Mandal, G. Majumdar", title: "Modelling and prediction of micro-hardness of electroless Ni-P coatings using response surface methodology and fuzzy logic", venue: "Jordan Journal of Mechanical and Industrial Engineering", year: 2022, details: "vol. 16, no. 5, pp. 729–742, Dec. 2022. ISSN 1995-6665" },
  { category: "Journals", authors: "P. Datta, A. Chakravarty, R. Saha, S. Chaudhuri, K. Ghosh, A. Mukhopadhyay, S. Sen, A. Dutta, P. Goyal", title: "Experimental investigation on the effect of initial pressure conditions during steam-water direct contact condensation in a horizontal pipe geometry", venue: "International Communications in Heat and Mass Transfer", year: 2021, details: "vol. 121, 105082, Feb. 2021. ISSN 0735-1933", doi: "10.1016/j.icheatmasstransfer.2020.105082" },
  { category: "Journals", authors: "S. Chaudhuri, R. Saha, A. Chatterjee, S. Mookherjee, D. Sanyal", title: "Adaptive neural-bias-sliding mode control of rugged electrohydraulic system motion by recurrent Hermite neural network", venue: "Control Engineering Practice", year: 2020, details: "vol. 103, 104588, Oct. 2020. ISSN 0967-0661", doi: "10.1016/j.conengprac.2020.104588" },
  { category: "Journals", authors: "S. Chaudhuri, R. Saha, A. Chatterjee, S. Mookherjee, D. Sanyal", title: "Development of a motion sensing system based on visual servoing of an eye-in-hand electrohydraulic parallel manipulator", venue: "IEEE Sensors Journal", year: 2020, details: "vol. 20, no. 14, pp. 8108–8116, Jul. 2020. ISSN 1558-1748", doi: "10.1109/JSEN.2020.2979490" },
  { category: "Journals", authors: "S. Sarkar, A. Mukherjee, S. Das, B. Ghosh, S. Chaudhuri, D. Bhattacharya, A. Sarbajna, R. Gachhui", title: "Nitrogen deprivation elicits dimorphism, capsule biosynthesis and autophagy in Papiliotrema laurentii strain RY1", venue: "Micron", year: 2019, details: "vol. 124, 102708, Sep. 2019. ISSN 0968-4328", doi: "10.1016/j.micron.2019.102708" },
  { category: "Journals", authors: "S. Das, S. Biswas, S. Chaudhuri, A. Bhattacharyya, B. Das", title: "A nuclear zip code in SKS1 mRNA promotes its slow export, nuclear retention, and degradation by the nuclear exosome/DRN in Saccharomyces cerevisiae", venue: "Journal of Molecular Biology", year: 2019, details: "vol. 431, no. 19, pp. 3626–3646, Sep. 2019. ISSN 0022-2836", doi: "10.1016/j.jmb.2019.07.005" },
  { category: "Conference Proceedings", authors: "S. Chaudhuri, H. Ramezani, J. Jouffroy", title: "Ensuring safe roll dynamics in marine vessels based on a safety-enhanced control framework", venue: "International Conference on Electrical, Computer and Energy Technologies (ICECET)", year: 2026, details: "Presented" },
  { category: "Conference Proceedings", authors: "Z. Gniewosz, S. Chaudhuri, H. Ramezani", title: "Torque vectoring-based active yaw control for enhanced vehicle handling and stability using a digital twin framework", venue: "INCOM 2026, Kolkata, India", year: 2026, details: "Jan. 2026. Presented" },
  { category: "Conference Proceedings", authors: "S. Chaudhuri, H. Ramezani, J. Jouffroy", title: "Remarks on augmenting stability and safety in nominal controllers: a practical perspective", venue: "European Control Conference (ECC), Thessaloniki, Greece", year: 2025, doi: "10.23919/ECC65951.2025.11187095" },
  { category: "Conference Proceedings", authors: "H. Ramezani, S. Chaudhuri, J. Jouffroy, A. Baurichter, S.M. Hansen", title: "On roll stabilisation using a canting keel", venue: "62nd IEEE Conference on Decision and Control (CDC), Singapore", year: 2023, details: "Dec. 2023", doi: "10.1109/CDC49753.2023.10384049" },
  { category: "Conference Proceedings", authors: "S. Chaudhuri, H. Ramezani, J. Jouffroy", title: "Investigation of marine vessels equipped with an airkeel subject to wave-induced disturbances", venue: "IEEE Conference on Control Technology and Applications (CCTA), Bridgetown, Barbados", year: 2023, details: "Aug. 2023", doi: "10.1109/CCTA54093.2023.10252537" },
  { category: "Conference Proceedings", authors: "S. Chaudhuri, H. Ramezani, J. Jouffroy", title: "Modelling and control of a canting-keel based ship roll stabilization system for crane operations", venue: "IEEE International Conference on Systems, Man, and Cybernetics (SMC), Prague, Czech Republic", year: 2022, details: "Oct. 2022", doi: "10.1109/SMC53654.2022.9945570" },
  { category: "Conference Proceedings", authors: "R. Bhattacharjee, S. Kundu, S. Chaudhuri", title: "Evaluation of workspace and coupled motions of an electrohydraulic parallel manipulator", venue: "Fourth International Conference on Electrical, Computer and Communication Technologies (ICECCT), Erode, India", year: 2021, details: "Sep. 2021", doi: "10.1109/ICECCT52121.2021.9616672" },
  { category: "Conference Proceedings", authors: "S. Kundu, R. Bhattacharjee, S. Chaudhuri", title: "Evaluation of fuzzy-logic based position control strategies for an electrohydraulic actuation system", venue: "International Conference on Advances in Electrical, Computing, Communication and Sustainable Technologies (ICAECT), Bhilai, India", year: 2021, details: "Feb. 2021", doi: "10.1109/ICAECT49130.2021.9392479" },
  { category: "Conference Proceedings", authors: "S. Chaudhuri, R. Saha, S. Mookherjee, D. Sanyal, A. Chatterjee", title: "Visual sensing based adaptive sliding mode control of position tracking in electrohydraulic systems", venue: "Second International Conference on Control, Instrumentation, Energy & Communication (CIEC), Kolkata, India", year: 2016, details: "Jan. 2016", doi: "10.1109/CIEC.2016.7513762" },
  { category: "Conference Proceedings", authors: "S. Chaudhuri, S. Mookherjee, D. Sanyal", title: "Adaptive force tracking in electrohydraulic system with first-order sliding mode control", venue: "IEEE First International Conference on Control, Measurement and Instrumentation (CMI), Kolkata, India", year: 2016, details: "Jan. 2016", doi: "10.1109/CMI.2016.7413759" },
  { category: "Conference Proceedings", authors: "S. Dasmahapatra, S. Chaudhuri, P. Mandal, S. Mookherjee, R. Saha", title: "Fuzzy-PI control of motion tracking by an electrohydraulic system with multiple nonlinearities", venue: "IET Michael Faraday International Summit, Kolkata, India", year: 2015, details: "Sep. 2015", doi: "10.1049/cp.2015.1612" },
  { category: "Books", authors: "S. Chaudhuri", title: "Pressurised Water Nuclear Reactor: Dynamics, Modelling and Simulation", venue: "LAP Lambert Academic Publishing (OmniScriptum Publishing Group)", year: 2019, details: "164 pp. ISBN 978-620-0-09362-2" },
  { category: "Book Chapters", authors: "R. Bhattacharjee, S. Chaudhuri, A. Ganguly", title: "Robust control of pulsatile ventricular assist devices for patients with advanced heart failure", venue: "Proceedings of COMSYS 2022, Lecture Notes in Networks and Systems, Springer, Singapore", year: 2023, details: "pp. 331–341. ISBN 978-981-99-2679-4", doi: "10.1007/978-981-99-2680-0_29" },
  { category: "Book Chapters", authors: "S. Chaudhuri, S. Dasmahapatra, A. Chatterjee, R. Saha, S. Mookherjee, D. Sanyal", title: "Adaptive fuzzy-sliding mode control with fixed bias compensator for an electrohydraulic actuation system with hard nonlinearities", venue: "Fluid Mechanics and Fluid Power: Contemporary Research, Lecture Notes in Mechanical Engineering, Springer, New Delhi", year: 2017, details: "pp. 1223–1232. ISBN 978-81-322-2743-4", doi: "10.1007/978-81-322-2743-4_116" },
  { category: "Posters", authors: "S. Chaudhuri, H. Ramezani, and J. Jouffroy", title: "Project SAFEMARVEL and Project AMCOSTAR", venue: "Poster presented at IME Day, University of Southern Denmark (SDU), Odense, Denmark", year: 2025, details: "May 27, 2025", posterUrl: "/assets/IMEDay_Poster_SAFEMARVEL_AMCOSTAR.pdf", galleryId: "poster-odense-2025" },
];

export const researchPillars = [
  ["Dynamics & Control", "Adaptive, nonlinear, robust and optimal control of uncertain systems, with stability and closed-loop behaviour treated as design requirements."],
  ["Electrohydraulics & Stewart Platforms", "Real-time motion and force control, vision sensing and parallel manipulators built around industry-grade hydraulic actuation."],
  ["Marine Roll Stabilisation", "SAFEMARVEL and AMCOSTAR research spanning canting keels, Airkeel systems, CBF-QP safety filters and varying sea states."],
  ["Energy Systems", "Control and optimisation for refrigeration, heat pumps, thermal energy storage and maritime energy systems."],
  ["Engineering–Biology Interface", "Image processing and closed-loop control contributions to molecular biology, cell biology and biomedical devices."],
] as const;

export const skills = [
  ["Control theory & algorithms", "Adaptive and nonlinear control; CBF and QP safety filters; MPC; sliding mode; neural-network, fuzzy, learning-based, reinforcement-learning, robust and optimal control."],
  ["Modelling & simulation", "Nonlinear dynamic modelling, model-based design, digital twins, parameter identification, Kalman filtering, state estimation and observer design."],
  ["Application domains", "Marine motion control, roll stabilisation, electrohydraulic actuation, parallel manipulators, refrigeration, heat pumps, vehicle dynamics and robotics."],
  ["Real-time implementation", "MIL, SIL and HIL; Speedgoat, NI cRIO and myRIO, DAQ; CAN, SPI, I²C, UART, RS-485; IMUs, encoders, LVDTs, pressure/flow sensors and load cells."],
  ["Actuation & drives", "Servo, proportional and servo-proportional valves (Rexroth, Eaton, Moog); motor control, VFD, hydraulic test benches and Stewart platforms."],
  ["Tools", "MATLAB/Simulink and Simscape, LabVIEW and the NI toolchain, Automation Studio and LaTeX."],
] as const;